| Part    | Topics                                              | Questions |
| ------- | --------------------------------------------------- | --------- |
| Part 1  | Basics (head, tail, shape, columns, info, describe) | 1–10      |
| Part 2  | Filtering & Selection                               | 11–20     |
| Part 3  | Sorting, Aggregation & Statistics                   | 21–30     |
| Part 4  | Missing Values & Duplicates                         | 31–40     |
| Part 5  | String Operations & Datetime                        | 41–50     |
| Part 6  | GroupBy & Aggregation                               | 51–60     |
| Part 7  | Merge, Join, Concat & Pivot                         | 61–70     |
| Part 8  | Apply, Map, Lambda & Functions                      | 71–80     |

| EmployeeID | Name   | Department | Age | Gender | Salary | Experience | City      | JoiningDate | Rating |
| ---------- | ------ | ---------- | --- | ------ | ------ | ---------- | --------- | ----------- | ------ |
| 101        | Amit   | HR         | 25  | Male   | 35000  | 2          | Pune      | 2021-05-10  | 4.2    |
| 102        | Priya  | IT         | 30  | Female | 70000  | 6          | Mumbai    | 2018-07-15  | 4.8    |
| 103        | Rahul  | Finance    | 28  | Male   | 55000  | 4          | Delhi     | 2020-01-20  | 4.1    |
| 104        | Sneha  | IT         | 35  | Female | 90000  | 10         | Bangalore | 2015-09-12  | 4.9    |
| 105        | Arjun  | Sales      | 27  | Male   | 45000  | 3          | Hyderabad | 2021-03-18  | 3.9    |
| 106        | Neha   | HR         | 29  | Female | 50000  | 5          | Pune      | 2019-11-25  | 4.3    |
| 107        | Karan  | Finance    | 40  | Male   | 100000 | 15         | Delhi     | 2010-04-01  | 4.7    |
| 108        | Pooja  | Sales      | 31  | Female | 65000  | 7          | Mumbai    | 2017-06-30  | 4.5    |
| 109        | Vivek  | IT         | 26  | Male   | 60000  | 3          | Bangalore | 2022-01-05  | 4.0    |
| 110        | Anjali | Marketing  | 33  | Female | 75000  | 8          | Chennai   | 2016-08-17  | 4.6    |

### Q. Convert this data into data frame

In [ ]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Arjun", "Neha", "Karan", "Pooja", "Vivek", "Anjali"],
    "Department": ["HR", "IT", "Finance", "IT", "Sales", "HR", "Finance", "Sales", "IT", "Marketing"],
    "Age": [25, 30, 28, 35, 27, 29, 40, 31, 26, 33],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Salary": [35000, 70000, 55000, 90000, 45000, 50000, 100000, 65000, 60000, 75000],
    "Experience": [2, 6, 4, 10, 3, 5, 15, 7, 3, 8],
    "City": ["Pune", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Pune", "Delhi", "Mumbai", "Bangalore", "Chennai"],
    "JoiningDate": [
        "2021-05-10", "2018-07-15", "2020-01-20", "2015-09-12", "2021-03-18",
        "2019-11-25", "2010-04-01", "2017-06-30", "2022-01-05", "2016-08-17"
    ],
    "Rating": [4.2, 4.8, 4.1, 4.9, 3.9, 4.3, 4.7, 4.5, 4.0, 4.6]
})

# JoiningDate to datetime
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])

# Display DataFrame
print(df)

   EmployeeID    Name Department  Age  Gender  Salary  Experience       City  \
0         101    Amit         HR   25    Male   35000           2       Pune
1         102   Priya         IT   30  Female   70000           6     Mumbai
2         103   Rahul    Finance   28    Male   55000           4      Delhi
3         104   Sneha         IT   35  Female   90000          10  Bangalore
4         105   Arjun      Sales   27    Male   45000           3  Hyderabad
5         106    Neha         HR   29  Female   50000           5       Pune
6         107   Karan    Finance   40    Male  100000          15      Delhi
7         108   Pooja      Sales   31  Female   65000           7     Mumbai
8         109   Vivek         IT   26    Male   60000           3  Bangalore
9         110  Anjali  Marketing   33  Female   75000           8    Chennai

  JoiningDate  Rating
0  2021-05-10     4.2
1  2018-07-15     4.8
2  2020-01-20     4.1
3  2015-09-12     4.9
4  2021-03-18     3.9
5  2019-11-25     4.3
6  2010-04-01     4.7
7  2017-06-30     4.5
8  2022-01-05     4.0
9  2016-08-17     4.6

### 1. Display the first five rows.

In [ ]:
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9

### 2. Display the last five rows.

In [ ]:
df.tail()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 3. Find the number of rows and columns.

In [ ]:
df.shape

(10, 10)

### 4. Display column names.

In [ ]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Gender', 'Salary',
       'Experience', 'City', 'JoiningDate', 'Rating'],
      dtype='object')

### 5. Display data types.

In [ ]:
df.dtypes

EmployeeID              int64
Name                   object
Department             object
Age                     int64
Gender                 object
Salary                  int64
Experience              int64
City                   object
JoiningDate    datetime64[ns]
Rating                float64
dtype: object

### 6. Display dataset information.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   10 non-null     int64
 1   Name         10 non-null     object
 2   Department   10 non-null     object
 3   Age          10 non-null     int64
 4   Gender       10 non-null     object
 5   Salary       10 non-null     int64
 6   Experience   10 non-null     int64
 7   City         10 non-null     object
 8   JoiningDate  10 non-null     datetime64[ns]
 9   Rating       10 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 932.0+ bytes

### 7. Generate summary statistics.

In [ ]:
df.describe()

,EmployeeID,Age,Salary,Experience,JoiningDate,Rating
count,10.00000,10.000000,10.000000,10.000000,10,10.000000
mean,105.50000,30.400000,64500.000000,6.300000,2018-04-24 19:12:00,4.400000
min,101.00000,25.000000,35000.000000,2.000000,2010-04-01 00:00:00,3.900000
25%,103.25000,27.250000,51250.000000,3.250000,2016-11-04 06:00:00,4.125000
50%,105.50000,29.500000,62500.000000,5.500000,2019-03-21 00:00:00,4.400000
75%,107.75000,32.500000,73750.000000,7.750000,2020-12-02 06:00:00,4.675000
max,110.00000,40.000000,100000.000000,15.000000,2022-01-05 00:00:00,4.900000
std,3.02765,4.575296,20062.402648,3.945462,NaN,0.349603

### 8. Check missing values.

In [ ]:
df.isnull().sum()

EmployeeID     0
Name           0
Department     0
Age            0
Gender         0
Salary         0
Experience     0
City           0
JoiningDate    0
Rating         0
dtype: int64

### 9. Display only the Name column.

In [ ]:
df["Name"]

0      Amit
1     Priya
2     Rahul
3     Sneha
4     Arjun
5      Neha
6     Karan
7     Pooja
8     Vivek
9    Anjali
Name: Name, dtype: object

### 10. Display Name and Salary columns.

In [ ]:
df[["Name", "Salary"]]

     Name  Salary
0    Amit   35000
1   Priya   70000
2   Rahul   55000
3   Sneha   90000
4   Arjun   45000
5    Neha   50000
6   Karan  100000
7   Pooja   65000
8   Vivek   60000
9  Anjali   75000

### 11. Find employee names older than 30.

In [ ]:
df[df["Age"] > 30]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 12. Find IT department employees.

In [ ]:
df[df["Department"] == "IT"]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0

### 13. Find employees earning more than ₹60,000.

In [ ]:
df[df["Salary"] > 60000]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 14. Display only female employees.

In [ ]:
df[df["Gender"] == "Female"]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 15. Display employees from Pune.

In [ ]:
df[df["City"] == "Pune"]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3

### 16. Count total employees.

In [ ]:
len(df)

10

### 17. Count male employees.

In [ ]:
(df["Gender"] == "Male").sum()

np.int64(5)

### 18. Count female employees.

In [ ]:
(df["Gender"] == "Female").sum()

np.int64(5)

### 19. Find maximum salary.

In [ ]:
df["Salary"].max()

100000

### 20. Find minimum salary.

In [ ]:
df["Salary"].min()

35000

### 21. Average Salary

In [ ]:
df["Salary"].mean()

np.float64(64500.0)

### 22. Median Salary

In [ ]:
df["Salary"].median()

62500.0

### 23. Highest-Paid Employee

In [ ]:
df[df["Salary"] == df["Salary"].max()]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7

### 24. Lowest-Paid Employee

In [ ]:
df[df["Salary"] == df["Salary"].min()]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2

### 25. Employees with More Than 5 Years of Experience

In [ ]:
df[df["Experience"] > 5]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 26. IT Employees with Salary > ₹70,000

In [ ]:
df[(df["Department"] == "IT") & (df["Salary"] > 70000)]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9

### 27. Sort Salary (Ascending)

In [ ]:
df.sort_values(by="Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7

### 28. Sort Salary (Descending)

In [ ]:
df.sort_values(by="Salary", ascending=False)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2

### 29. Top 3 Highest-Paid Employees

In [ ]:
df.nlargest(3, "Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 30. Bottom 3 Lowest Salaries

In [ ]:
df.nsmallest(3, "Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3

### 31. Count Employees in Each Department

In [ ]:
df["Department"].value_counts()

Department
IT           3
HR           2
Finance      2
Sales        2
Marketing    1
Name: count, dtype: int64

### 32. Average Salary by Department

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
Finance      77500.000000
HR           42500.000000
IT           73333.333333
Marketing    75000.000000
Sales        55000.000000
Name: Salary, dtype: float64

### 33. Count Employees by City

In [ ]:
df.groupby("City").size()

City
Bangalore    2
Chennai      1
Delhi        2
Hyderabad    1
Mumbai       2
Pune         2
dtype: int64

In [ ]:
df["City"].value_counts()

City
Pune         2
Mumbai       2
Delhi        2
Bangalore    2
Hyderabad    1
Chennai      1
Name: count, dtype: int64

### 34. Average Rating by Department

In [ ]:
df.groupby("Department")["Rating"].mean()

Department
Finance      4.400000
HR           4.250000
IT           4.566667
Marketing    4.600000
Sales        4.200000
Name: Rating, dtype: float64

### 35. Maximum Salary by Department

In [ ]:
df.groupby("Department")["Salary"].max()

Department
Finance      100000
HR            50000
IT            90000
Marketing     75000
Sales         65000
Name: Salary, dtype: int64

### 36. Minimum Salary by City

In [ ]:
df.groupby("City")["Salary"].min()

City
Bangalore    60000
Chennai      75000
Delhi        55000
Hyderabad    45000
Mumbai       65000
Pune         35000
Name: Salary, dtype: int64

### 37. Rename Columns

In [ ]:
df.rename(columns={
    "Salary": "MonthlySalary",
    "Experience": "YearsExperience"
})

,EmployeeID,Name,Department,Age,Gender,MonthlySalary,YearsExperience,City,JoiningDate,Rating
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6

### 38. Add Bonus Column (10%)

In [ ]:
df["Bonus"] = df["Salary"] * 0.10
df['Bonus']

0     3500.0
1     7000.0
2     5500.0
3     9000.0
4     4500.0
5     5000.0
6    10000.0
7     6500.0
8     6000.0
9     7500.0
Name: Bonus, dtype: float64

### 39. Add Tax Column (5%)

In [ ]:
df["Tax"] = df["Salary"] * 0.05

NameError: name 'df' is not defined

### 40. Convert JoiningDate to Datetime

In [ ]:
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])
df["JoiningDate"].dtype

dtype('<M8[ns]')

>In pandas, <M8[ns] is the low-level NumPy representation for the datetime64[ns] data type, which represents dates and times with nanosecond precision

### 41. Calculate Years Since Joining

In [ ]:
df["YearsSinceJoining"] = (
    pd.Timestamp.today() - df["JoiningDate"]
).dt.days // 365

### 42. Set EmployeeID as Index

In [ ]:
df.set_index("EmployeeID", inplace=True)

### 43. Reset Index

In [ ]:
df.reset_index(inplace=True)

### 44. Remove Duplicate Rows

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(10, 13)

### 45. Check Unique Cities

In [ ]:
df["City"].unique()

array(['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai'],
      dtype=object)

### 46. Count Unique Cities

In [ ]:
df["City"].nunique()

6

### 47. Check Unique Departments

In [ ]:
df["Department"].unique()

array(['HR', 'IT', 'Finance', 'Sales', 'Marketing'], dtype=object)

### 48. Count Unique Departments

In [ ]:
df["Department"].nunique()

5

### 49. Filter with Multiple Conditions

In [ ]:
df[
    (df["Salary"] > 50000) &
    (df["Experience"] > 5)
]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6,7500.0,3750.0,9

### 50. Using query()

In [ ]:
df.query("Salary > 50000 and Experience > 5")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6,7500.0,3750.0,9

### 51. Using loc[]

In [ ]:
df.loc[:, ["Name", "Salary"]]

     Name  Salary
0    Amit   35000
1   Priya   70000
2   Rahul   55000
3   Sneha   90000
4   Arjun   45000
5    Neha   50000
6   Karan  100000
7   Pooja   65000
8   Vivek   60000
9  Anjali   75000

In [ ]:
df.loc[0:4]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1,5500.0,2750.0,6
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9,4500.0,2250.0,5

### 52. Using iloc[]

In [ ]:
df.iloc[: ,[1,5]]

     Name  Salary
0    Amit   35000
1   Priya   70000
2   Rahul   55000
3   Sneha   90000
4   Arjun   45000
5    Neha   50000
6   Karan  100000
7   Pooja   65000
8   Vivek   60000
9  Anjali   75000

In [ ]:
df.iloc[0:5]

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1,5500.0,2750.0,6
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9,4500.0,2250.0,5

### 53. Random Sample

In [ ]:
df.sample(3)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9

### 54. Create Salary Categories using pd.cut()

In [ ]:
df["SalaryCategory"] = pd.cut(
    df["Salary"],
    bins=[0,40000,60000,80000,100000],
    labels=["Low","Medium","High","Very High"]
)

In [ ]:
df["SalaryCategory"]

0          Low
1         High
2       Medium
3    Very High
4       Medium
5       Medium
6    Very High
7         High
8       Medium
9         High
Name: SalaryCategory, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

### 55. Sort by Department then Salary

In [ ]:
df.sort_values(
    by=["Department","Salary"],
    ascending=[True,False]
)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining,SalaryCategory
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16,Very High
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1,5500.0,2750.0,6,Medium
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3,5000.0,2500.0,6,Medium
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5,Low
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10,Very High
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8,High
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0,6000.0,3000.0,4,Medium
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6,7500.0,3750.0,9,High
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9,High
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9,4500.0,2250.0,5,Medium

### 56. nlargest()

In [ ]:
df.nlargest(5, "Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining,SalaryCategory
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16,Very High
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10,Very High
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6,7500.0,3750.0,9,High
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8,High
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9,High

### 57. nsmallest()

In [ ]:
df.nsmallest(5, "Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining,SalaryCategory
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5,Low
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9,4500.0,2250.0,5,Medium
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3,5000.0,2500.0,6,Medium
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1,5500.0,2750.0,6,Medium
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0,6000.0,3000.0,4,Medium

### 58. assign()

In [ ]:
df = df.assign(
    HRA=df["Salary"]*0.20,
    PF=df["Salary"]*0.12
)

### 59. pipe()

In [ ]:
def add_bonus(data):
    data["Bonus"] = data["Salary"] * 0.10
    return data

df.pipe(add_bonus)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,JoiningDate,Rating,Bonus,Tax,YearsSinceJoining,SalaryCategory,HRA,PF
0,101,Amit,HR,25,Male,35000,2,Pune,2021-05-10,4.2,3500.0,1750.0,5,Low,7000.0,4200.0
1,102,Priya,IT,30,Female,70000,6,Mumbai,2018-07-15,4.8,7000.0,3500.0,8,High,14000.0,8400.0
2,103,Rahul,Finance,28,Male,55000,4,Delhi,2020-01-20,4.1,5500.0,2750.0,6,Medium,11000.0,6600.0
3,104,Sneha,IT,35,Female,90000,10,Bangalore,2015-09-12,4.9,9000.0,4500.0,10,Very High,18000.0,10800.0
4,105,Arjun,Sales,27,Male,45000,3,Hyderabad,2021-03-18,3.9,4500.0,2250.0,5,Medium,9000.0,5400.0
5,106,Neha,HR,29,Female,50000,5,Pune,2019-11-25,4.3,5000.0,2500.0,6,Medium,10000.0,6000.0
6,107,Karan,Finance,40,Male,100000,15,Delhi,2010-04-01,4.7,10000.0,5000.0,16,Very High,20000.0,12000.0
7,108,Pooja,Sales,31,Female,65000,7,Mumbai,2017-06-30,4.5,6500.0,3250.0,9,High,13000.0,7800.0
8,109,Vivek,IT,26,Male,60000,3,Bangalore,2022-01-05,4.0,6000.0,3000.0,4,Medium,12000.0,7200.0
9,110,Anjali,Marketing,33,Female,75000,8,Chennai,2016-08-17,4.6,7500.0,3750.0,9,High,15000.0,9000.0

### 60. apply() to Classify Salary

In [ ]:
def classify_salary(salary):
    if salary < 50000:
        return "Low"
    elif salary < 80000:
        return "Medium"
    else:
        return "High"

df["SalaryLevel"] = df["Salary"].apply(classify_salary)

In [ ]:
df["SalaryLevel"] = df["Salary"].apply(
    lambda x: "High"
    if x >= 80000
    else "Medium"
    if x >= 50000
    else "Low"
)

### Bonus 1. map() to Encode Gender

In [ ]:
df["GenderCode"] = df["Gender"].map({
    "Male": 1,
    "Female": 0
})

### Bonus 2. replace() to Rename Departments

In [ ]:
df["Department"] = df["Department"].replace({
    "HR": "Human Resources",
    "IT": "Information Technology"
})

### Bonus 3. Export to CSV

In [ ]:
df.to_csv("employee_output.csv", index=False)

### Bonus 4. Export to Excel

In [ ]:
df.to_excel("employee_output.xlsx", index=False)

### 61. Create a Pivot Table of Average Salary by City and Department

In [ ]:
pivot = df.pivot_table(
    values="Salary",
    index="City",
    columns="Department",
    aggfunc="mean"
)

print(pivot)

Department  Finance  Human Resources  Information Technology  Marketing  \
City
Bangalore       NaN              NaN                 75000.0        NaN
Chennai         NaN              NaN                     NaN    75000.0
Delhi       77500.0              NaN                     NaN        NaN
Hyderabad       NaN              NaN                     NaN        NaN
Mumbai          NaN              NaN                 70000.0        NaN
Pune            NaN          42500.0                     NaN        NaN

Department    Sales
City
Bangalore       NaN
Chennai         NaN
Delhi           NaN
Hyderabad   45000.0
Mumbai      65000.0
Pune            NaN

### 62. Use groupby() with Multiple Aggregations

In [ ]:
result = df.groupby("Department").agg({
    "Salary": ["min", "max", "mean", "sum"],
    "Age": ["min", "max", "mean"],
    "Rating": ["mean", "max"]
})

print(result)

                       Salary                               Age      \
                          min     max          mean     sum min max
Department
Finance                 55000  100000  77500.000000  155000  28  40
Human Resources         35000   50000  42500.000000   85000  25  29
Information Technology  60000   90000  73333.333333  220000  26  35
Marketing               75000   75000  75000.000000   75000  33  33
Sales                   45000   65000  55000.000000  110000  27  31

                                     Rating
                             mean      mean  max
Department
Finance                 34.000000  4.400000  4.7
Human Resources         27.000000  4.250000  4.3
Information Technology  30.333333  4.566667  4.9
Marketing               33.000000  4.600000  4.6
Sales                   29.000000  4.200000  4.5

### 63. Rank Employees by Salary

In [ ]:
df["SalaryRank"] = df["Salary"].rank(ascending=False)

print(df)

   EmployeeID    Name              Department  Age  Gender  Salary  \
0         101    Amit         Human Resources   25    Male   35000
1         102   Priya  Information Technology   30  Female   70000
2         103   Rahul                 Finance   28    Male   55000
3         104   Sneha  Information Technology   35  Female   90000
4         105   Arjun                   Sales   27    Male   45000
5         106    Neha         Human Resources   29  Female   50000
6         107   Karan                 Finance   40    Male  100000
7         108   Pooja                   Sales   31  Female   65000
8         109   Vivek  Information Technology   26    Male   60000
9         110  Anjali               Marketing   33  Female   75000

   Experience       City JoiningDate  Rating    Bonus     Tax  \
0           2       Pune  2021-05-10     4.2   3500.0  1750.0
1           6     Mumbai  2018-07-15     4.8   7000.0  3500.0
2           4      Delhi  2020-01-20     4.1   5500.0  2750.0
3          10  Bangalore  2015-09-12     4.9   9000.0  4500.0
4           3  Hyderabad  2021-03-18     3.9   4500.0  2250.0
5           5       Pune  2019-11-25     4.3   5000.0  2500.0
6          15      Delhi  2010-04-01     4.7  10000.0  5000.0
7           7     Mumbai  2017-06-30     4.5   6500.0  3250.0
8           3  Bangalore  2022-01-05     4.0   6000.0  3000.0
9           8    Chennai  2016-08-17     4.6   7500.0  3750.0

   YearsSinceJoining SalaryCategory      HRA       PF SalaryLevel  GenderCode  \
0                  5            Low   7000.0   4200.0         Low           1
1                  8           High  14000.0   8400.0      Medium           0
2                  6         Medium  11000.0   6600.0      Medium           1
3                 10      Very High  18000.0  10800.0        High           0
4                  5         Medium   9000.0   5400.0         Low           1
5                  6         Medium  10000.0   6000.0      Medium           0
6                 16      Very High  20000.0  12000.0        High           1
7                  9           High  13000.0   7800.0      Medium           0
8                  4         Medium  12000.0   7200.0      Medium           1
9                  9           High  15000.0   9000.0      Medium           0

   SalaryRank
0        10.0
1         4.0
2         7.0
3         2.0
4         9.0
5         8.0
6         1.0
7         5.0
8         6.0
9         3.0

### 64. Calculate Cumulative Salary

In [ ]:
df["CumulativeSalary"] = df["Salary"].cumsum()

print(df)

   EmployeeID    Name              Department  Age  Gender  Salary  \
0         101    Amit         Human Resources   25    Male   35000
1         102   Priya  Information Technology   30  Female   70000
2         103   Rahul                 Finance   28    Male   55000
3         104   Sneha  Information Technology   35  Female   90000
4         105   Arjun                   Sales   27    Male   45000
5         106    Neha         Human Resources   29  Female   50000
6         107   Karan                 Finance   40    Male  100000
7         108   Pooja                   Sales   31  Female   65000
8         109   Vivek  Information Technology   26    Male   60000
9         110  Anjali               Marketing   33  Female   75000

   Experience       City JoiningDate  Rating    Bonus     Tax  \
0           2       Pune  2021-05-10     4.2   3500.0  1750.0
1           6     Mumbai  2018-07-15     4.8   7000.0  3500.0
2           4      Delhi  2020-01-20     4.1   5500.0  2750.0
3          10  Bangalore  2015-09-12     4.9   9000.0  4500.0
4           3  Hyderabad  2021-03-18     3.9   4500.0  2250.0
5           5       Pune  2019-11-25     4.3   5000.0  2500.0
6          15      Delhi  2010-04-01     4.7  10000.0  5000.0
7           7     Mumbai  2017-06-30     4.5   6500.0  3250.0
8           3  Bangalore  2022-01-05     4.0   6000.0  3000.0
9           8    Chennai  2016-08-17     4.6   7500.0  3750.0

   YearsSinceJoining SalaryCategory      HRA       PF SalaryLevel  GenderCode  \
0                  5            Low   7000.0   4200.0         Low           1
1                  8           High  14000.0   8400.0      Medium           0
2                  6         Medium  11000.0   6600.0      Medium           1
3                 10      Very High  18000.0  10800.0        High           0
4                  5         Medium   9000.0   5400.0         Low           1
5                  6         Medium  10000.0   6000.0      Medium           0
6                 16      Very High  20000.0  12000.0        High           1
7                  9           High  13000.0   7800.0      Medium           0
8                  4         Medium  12000.0   7200.0      Medium           1
9                  9           High  15000.0   9000.0      Medium           0

   SalaryRank  CumulativeSalary
0        10.0             35000
1         4.0            105000
2         7.0            160000
3         2.0            250000
4         9.0            295000
5         8.0            345000
6         1.0            445000
7         5.0            510000
8         6.0            570000
9         3.0            645000

### 65. Find Duplicate Rows

In [ ]:
duplicates = df[df.duplicated()]

print(duplicates)

Empty DataFrame
Columns: [EmployeeID, Name, Department, Age, Gender, Salary, Experience, City, JoiningDate, Rating, Bonus, Tax, YearsSinceJoining, SalaryCategory, HRA, PF, SalaryLevel, GenderCode, SalaryRank, CumulativeSalary]
Index: []

### 66. Find Unique Ratings

In [ ]:
print(df["Rating"].unique())

[4.2 4.8 4.1 4.9 3.9 4.3 4.7 4.5 4.  4.6]