In [3]:
import numpy as np
import pandas as pd

In [16]:
dict_1 = pd.DataFrame({
    'name':['prince','mayur','smit','hardik'],
    'roll_no':[101,102,103,104]
})
dict_1

     name  roll_no
0  prince      101
1   mayur      102
2    smit      103
3  hardik      104

In [41]:
dict_2 = pd.DataFrame({
    'name':['neel','yash','rahul','tanish'],
    'roll_no':[105,106,107,108]
})
dict_2

     name  roll_no
0    neel      105
1    yash      106
2   rahul      107
3  tanish      108

In [18]:
data_fr = {
    'df1': dict_1,
    'df2': dict_2
}
data_fr

{'df1':      name  roll_no
 0  prince      101
 1   mayur      102
 2    smit      103
 3  hardik      104,
 'df2':    name  roll_no
 0  neel      105
 1  yash      106}

In [42]:
merge_df = pd.merge(dict_1,dict_2, on = 'roll_no')
merge_df

Empty DataFrame
Columns: [name_x, roll_no, name_y]
Index: []

In [43]:
df = pd.DataFrame(merge_df)
df

Empty DataFrame
Columns: [name_x, roll_no, name_y]
Index: []

In [21]:
df = pd.read_csv(r"D:\ML_Trainning\googleplaystore.csv")

In [22]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [54]:
merge = pd.merge(dict_3, dict_4, on = 'ID')
merge

   ID  roll_no    name
0   1      101  prince
1   2      102   mayur
2   3      103    smit

In [48]:
merge_in = pd.merge(dict_3, dict_4, on = 'ID', how = 'inner') # jo common hogi usko print karta heii orr null value skip hogi
merge_in

   ID  roll_no    name
0   1      101  prince
1   2      102   mayur
2   3      103    smit
3   4      104  hardik

In [57]:
dict_3 = pd.DataFrame({
    'ID':[1,2,3,5],
    'roll_no':[101,102,103,104]
})
dict_3

   ID  roll_no
0   1      101
1   2      102
2   3      103
3   5      104

In [58]:
dict_4 = pd.DataFrame({
    'ID':[1,2,3,4],
    'name':['prince','mayur','smit','hardik']
})
dict_4

   ID    name
0   1  prince
1   2   mayur
2   3    smit
3   4  hardik

In [59]:
merge_left = pd.merge(dict_3, dict_4, on = 'ID', how = 'left') # left ki sari value print karega or right side se null ko print karega
merge_left

   ID  roll_no    name
0   1      101  prince
1   2      102   mayur
2   3      103    smit
3   5      104     NaN

In [60]:
merge_left = pd.merge(dict_3, dict_4, on = 'ID', how = 'right') # right ki sari value print karega or left side se null ko print karega
merge_left

   ID  roll_no    name
0   1    101.0  prince
1   2    102.0   mayur
2   3    103.0    smit
3   4      NaN  hardik

In [62]:
merge_left = pd.merge(dict_3, dict_4, on = 'ID', how = 'outer') 
merge_left

   ID  roll_no    name
0   1    101.0  prince
1   2    102.0   mayur
2   3    103.0    smit
3   4      NaN  hardik
4   5    104.0     NaN

In [73]:
dt_1 = pd.DataFrame({
    'User_ID':[101,102,103],
    'Name':['prince','smit','mayur']
}, index = [11,12,13])
print(dt_1)

dt_2 = pd.DataFrame({
    'User_ID':[101,102,104],
    'City':['jetpur','botad','vadhvan']
}, index = [100,200,300])
print(dt_2)

index_acc = pd.merge(dt_1, dt_2, left_index = True, right_index = True)
index_acc

    User_ID    Name
11      101  prince
12      102    smit
13      103   mayur
     User_ID     City
100      101   jetpur
200      102    botad
300      104  vadhvan

Empty DataFrame
Columns: [User_ID_x, Name, User_ID_y, City]
Index: []

In [74]:
dt_21 = pd.DataFrame({
    'User_ID':[101,102,103],
    'Name':['prince','smit','mayur']
}, index = [11,12,13])
print(dt_1)

dt_22 = pd.DataFrame({
    'User_ID':[101,102,104],
    'City':['jetpur','botad','vadhvan']
}, index = [11,12,13])
print(dt_22)

index_acc = pd.merge(dt_21, dt_22, left_index = True, right_index = True)
index_acc

    User_ID    Name
11      101  prince
12      102    smit
13      103   mayur
    User_ID     City
11      101   jetpur
12      102    botad
13      104  vadhvan

    User_ID_x    Name  User_ID_y     City
11        101  prince        101   jetpur
12        102    smit        102    botad
13        103   mayur        104  vadhvan

# Missing value

In [76]:
data = {
    'age':[25,np.nan,34,27],
    'score':[56,78,np.nan,np.nan],
    'City':['jetpur',np.nan,np.nan,'rajkot']
}
dataf = pd.DataFrame(data)
dataf

    age  score    City
0  25.0   56.0  jetpur
1   NaN   78.0     NaN
2  34.0    NaN     NaN
3  27.0    NaN  rajkot

In [85]:
dataf.isnull()
# dataf.isnull().sum()

     age  score   City
0  False  False  False
1   True  False   True
2  False   True   True
3  False   True  False

In [81]:
dataf.notnull()
# dataf.notnull().sum()

     age  score   City
0   True   True   True
1  False   True  False
2   True  False  False
3   True  False   True

In [87]:
df_row = dataf.dropna()
df_row

    age  score    City
0  25.0   56.0  jetpur

In [88]:
df_row = dataf.dropna(axis=1)
df_row

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [90]:
df_row = dataf.dropna(subset=['age','City'])
df_row

    age  score    City
0  25.0   56.0  jetpur
3  27.0    NaN  rajkot

In [92]:
df_zero = dataf.fillna(0)
df_zero

    age  score    City
0  25.0   56.0  jetpur
1   0.0   78.0       0
2  34.0    0.0       0
3  27.0    0.0  rajkot

In [92]:
df_zero = dataf.fillna(0)
df_zero

    age  score    City
0  25.0   56.0  jetpur
1   0.0   78.0       0
2  34.0    0.0       0
3  27.0    0.0  rajkot