In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Color':['red','green','blue']
})
pd.get_dummies(df)

   Color_blue  Color_green  Color_red
0       False        False       True
1       False         True      False
2        True        False      False

In [4]:
pd.get_dummies(df, dtype = int)

   Color_blue  Color_green  Color_red
0           0            0          1
1           0            1          0
2           1            0          0

In [5]:
prefix = None

In [7]:
pd.get_dummies(df, dtype = int)

   Color_blue  Color_green  Color_red
0           0            0          1
1           0            1          0
2           1            0          0

In [8]:
pd.get_dummies(df, prefix = 'clr', dtype = int)

   clr_blue  clr_green  clr_red
0         0          0        1
1         0          1        0
2         1          0        0

In [9]:
df1 = pd.DataFrame({
    'color': ['blue','green'],
    'size': ['s' ,'m']
})

pd.get_dummies(df1)

   color_blue  color_green  size_m  size_s
0        True        False   False    True
1       False         True    True   False

In [11]:
pd.get_dummies(df1, prefix = ['c' , 's'], dtype = int)

   c_blue  c_green  s_m  s_s
0       1        0    0    1
1       0        1    1    0

In [12]:
pd.get_dummies(df1, prefix = 'color', prefix_sep = '-', dtype = int)

   color-blue  color-green  color-m  color-s
0           1            0        0        1
1           0            1        1        0

In [13]:
df2 = pd.DataFrame({
    'Color': ['Blue', 'Green', None, 'Pink']
})
pd.get_dummies(df2, dtype = int)

   Color_Blue  Color_Green  Color_Pink
0           1            0           0
1           0            1           0
2           0            0           0
3           0            0           1

In [17]:
df3 = pd.DataFrame({
    'Color': ['black', 'white', 'pink'],
    'Age': [21,25,26],
    'Gender':['M', 'F' , 'F']
})
pd.get_dummies(df3, dtype = int)

   Age  Color_black  Color_pink  Color_white  Gender_F  Gender_M
0   21            1           0            0         0         1
1   25            0           0            1         1         0
2   26            0           1            0         1         0

In [18]:
pd.get_dummies(df3, columns = ['Color'], dtype = int)

   Age Gender  Color_black  Color_pink  Color_white
0   21      M            1           0            0
1   25      F            0           0            1
2   26      F            0           1            0

In [19]:
pd.get_dummies(df3, columns = ['Color','Gender'], dtype = int)

   Age  Color_black  Color_pink  Color_white  Gender_F  Gender_M
0   21            1           0            0         0         1
1   25            0           0            1         1         0
2   26            0           1            0         1         0

In [21]:
pd.get_dummies(df3, sparse = True, dtype = int)

   Age  Color_black  Color_pink  Color_white  Gender_F  Gender_M
0   21            1           0            0         0         1
1   25            0           0            1         1         0
2   26            0           1            0         1         0

In [23]:
df4 = pd.DataFrame({
    'Gender':['Male','Female','Male']
})

In [24]:
pd.get_dummies(df4, dtype = int)

   Gender_Female  Gender_Male
0              0            1
1              1            0
2              0            1

In [28]:
pd.get_dummies(df4, drop_first = True, dtype = int)

   Gender_Male
0            1
1            0
2            1