## Empty series

In [2]:
import pandas as pd

In [3]:
scalar_s = pd.Series(1)
print(scalar_s)

0    1
dtype: int64

## Dictionary to series

In [4]:
dict = pd.Series({'a' : 1, 'b' : 2})
dict

a    1
b    2
dtype: int64

In [5]:
series_1 = pd.Series([2,3,4,5], index = ['a','b','c','d'])
series_1

a    2
b    3
c    4
d    5
dtype: int64

## indexing in series

In [6]:
sr_1 = pd.Series([1,2,3,4])
sr_2 = pd.Series([5,6,7,8])
print(sr_1)
print(sr_2)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64

In [8]:
sr_sum = sr_1 + sr_2
sr_sum

0     6
1     8
2    10
3    12
dtype: int64

In [10]:
sr_3 = pd.Series([6,3,9])

unique_sum = sr_2 + sr_3
print(unique_sum)

0    11.0
1     9.0
2    16.0
3     NaN
dtype: float64

## Dataframe

In [13]:
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

## Import Dataset

In [21]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [22]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", usecols = [1,3,5])
df

              Name  Inception           Expenses
0          Lamtone       2009  6,482,465 Dollars
1        Stripfind       2010    916,455 Dollars
2  Canecorporation       2012  7,591,189 Dollars
3         Mattouch       2013  7,429,377 Dollars
4        Techdrill       2009  7,435,363 Dollars
5         Techline       2006  5,470,303 Dollars
6          Cityace       2010  6,249,498 Dollars
7   Kayelectronics       2009  3,878,113 Dollars
8          Ganzlax       2011                NaN
9      Trantraxlax       2011  5,635,276 Dollars

In [23]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", skiprows = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [24]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", skiprows = [1,3,4])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
3,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
4,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
5,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
6,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [25]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", index_col = 'ID')
df

,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

## Header

In [26]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", header = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [31]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", names = ['A', 'B'])
df

,,,,,,A,B
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",nan,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [32]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10.csv", dtype = {'ID': 'float64', 'profit': 'float64'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5.0,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

## NaN values : 
### N/A, N/A N/A, NA, -1,QNAN

In [34]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10 - Copy.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [35]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10 - Copy.csv", na_values = 'not available')
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [36]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10 - Copy.csv", na_values = {'Revenue':'no value'} )
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,NaN,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [37]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10 - Copy.csv", keep_default_na = True)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [38]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_10 - Copy.csv", na_filter = False)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [39]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False     False   False   False
9  False  False     False      False    False     False   False   False

In [42]:
df.isnull().sum()

ID           0
Name         0
Industry     0
Inception    0
Revenue      0
Expenses     0
Profit       0
Growth       0
dtype: int64

In [41]:
df.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True    True
3  True  True      True       True     True      True    True    True
4  True  True      True       True     True      True    True    True
5  True  True      True       True     True      True    True    True
6  True  True      True       True     True      True    True    True
7  True  True      True       True     True      True    True    True
8  True  True      True       True     True      True    True    True
9  True  True      True       True     True      True    True    True

In [43]:
df.notnull().sum()

ID           10
Name         10
Industry     10
Inception    10
Revenue      10
Expenses     10
Profit       10
Growth       10
dtype: int64

In [45]:
import numpy as np
ser = pd.Series([1,2,3,np.nan,4,np.nan])
ser

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [46]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [47]:
ser.notnull()

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool

In [49]:
df = pd.read_csv(r"D:\Project\Jupyter_1\Fortune_5 nan values.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df['Expenses'].isnull().sum()

np.int64(6)

In [11]:
import pandas as pd
df = pd.read_csv(r"D:\ML_Trainning\Jupyter_1\Fortune_5 nan values.csv")
df

# df.isnull().sum()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df.iloc[4].isnull().sum()

np.int64(1)

In [50]:
df.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [51]:
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
df.dropna(axis=0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [53]:
df.dropna(how = 'any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [54]:
df.dropna(axis = 1, how = 'any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
df.dropna(how='all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [74]:
df.dropna(thresh=0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
df.dropna(thresh=1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [76]:
df.dropna(thresh=2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [78]:
df.dropna(subset = ['Expenses'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [79]:
df.fillna({'Expenses': 'none', 'Profit': 55})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",none,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",55.0,8%
5,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
6,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
7,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
8,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
9,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN

In [86]:
df.ffill()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
7,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
8,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
9,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%

In [82]:
pd.__version__

'3.0.3'

In [88]:
df.bfill()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","7,429,377 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Fillna methods limits

In [12]:
df.fillna(method = 'fill', limit = 2, axis = 1)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [13]:
df.replace(to_replace = 'Health', value = 'it serv')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,it serv,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,it serv,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.replace('IT Services','AI/ML')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,AI/ML,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,AI/ML,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.replace(10,15)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.replace({'Industry': 'Health'}, 'abc')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,abc,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,abc,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.replace('[A-Za-z',0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.replace('[A-Za-z]', 0 , regex = True)

    ID Name Industry  Inception       Revenue Expenses      Profit Growth
0  1.0    0        0     2009.0  $11,757,018         0   5274553.0    30%
1  2.0    0        0     2010.0  $12,329,371         0  11412916.0    20%
2  3.0    0        0     2012.0  $10,597,009       NaN   3005820.0     7%
3  4.0    0        0     2013.0  $14,026,934         0   6597557.0    26%
4  5.0    0        0     2009.0  $10,573,990         0         NaN     8%
5  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
6  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
7  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
8  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
9  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN

In [29]:
df.replace('[A-Za-z]', '0' , regex = True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,0000000,00 00000000,2009.0,"$11,757,018","6,482,465 0000000",5274553.0,30%
1,2.0,000000000,000000000 00000000,2010.0,"$12,329,371","916,455 0000000",11412916.0,20%
2,3.0,000000000000000,000000,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,00000000,00 00000000,2013.0,"$14,026,934","7,429,377 0000000",6597557.0,26%
4,5.0,000000000,000000,2009.0,"$10,573,990","7,435,363 0000000",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df.replace('[A-Za-z]', 'p' , regex = True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,ppppppp,pp pppppppp,2009.0,"$11,757,018","6,482,465 ppppppp",5274553.0,30%
1,2.0,ppppppppp,ppppppppp pppppppp,2010.0,"$12,329,371","916,455 ppppppp",11412916.0,20%
2,3.0,ppppppppppppppp,pppppp,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,pppppppp,pp pppppppp,2013.0,"$14,026,934","7,429,377 ppppppp",6597557.0,26%
4,5.0,ppppppppp,pppppp,2009.0,"$10,573,990","7,435,363 ppppppp",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df.replace({'Industry' ,'[A-Za-z]'}, 0 , regex = True)

    ID Name Industry  Inception       Revenue Expenses      Profit Growth
0  1.0    0        0     2009.0  $11,757,018         0   5274553.0    30%
1  2.0    0        0     2010.0  $12,329,371         0  11412916.0    20%
2  3.0    0        0     2012.0  $10,597,009       NaN   3005820.0     7%
3  4.0    0        0     2013.0  $14,026,934         0   6597557.0    26%
4  5.0    0        0     2009.0  $10,573,990         0         NaN     8%
5  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
6  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
7  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
8  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN
9  NaN  NaN      NaN        NaN           NaN      NaN         NaN    NaN

In [28]:
df.replace('Health', method = 'ffill')

TypeError: NDFrame.replace() got an unexpected keyword argument 'method'

## Interpolate

In [33]:
df = pd.read_csv(r"D:\ML_Trainning\Jupyter_1\student_results - copy.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.0,2.0,9.0,3.0,5,50.0
1,1002,10.0,6.0,8.0,2.0,0,80.0
2,1003,10.0,NaN,NaN,2.0,4,60.0
3,1004,11.0,NaN,NaN,1.0,5,45.0
4,1005,11.0,NaN,NaN,2.0,0,NaN
5,1006,11.0,10.0,7.0,0.0,0,NaN
6,1007,NaN,4.0,6.0,0.0,0,NaN
7,1008,NaN,10.0,NaN,NaN,0,90.0
8,1009,12.0,2.0,8.0,2.0,4,60.0
9,1010,12.0,6.0,9.0,1.0,0,85.0

In [34]:
df.interpolate()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [35]:
df.interpolate(method = 'linear')

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [36]:
df = pd.read_csv(r"D:\ML_Trainning\Jupyter_1\student_results - copy.csv", parse_dates = ['Study hrs'], index_col = 'Class')
df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14208\3805018175.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(r"D:\ML_Trainning\Jupyter_1\student_results - copy.csv", parse_dates = ['Study hrs'], index_col = 'Class')

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

## loc and iloc (loc = location, iloc = index location)

In [37]:
df = pd.read_csv(r"D:\ML_Trainning\Jupyter_1\student_results.xls")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [40]:
df.loc[:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [39]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [41]:
df.loc[4]

Student ID                1005
Class                       11
Study hrs                    4
Sleeping hrs                 7
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  75
Name: 4, dtype: int64

In [42]:
df.loc[[0,1,2,3]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45

In [44]:
df.loc[4,'Class']

np.int64(11)

In [46]:
df.loc[0:2, 'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [47]:
df.loc[df['Class'] < 11,['Percantege']]

   Percantege
0          50
1          80
2          60

In [48]:
df.loc[df['Study hrs'] > 7, ['Percantege']]

   Percantege
5          96
7          90

In [49]:
df.iloc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [50]:
df.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [51]:
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [52]:
df.iloc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80