# **DAY - 1 Numpy**

In [ ]:
list = [[12,13],[15,16]]
print(list[0][0] + list[1][1])

28

In [ ]:
import numpy as np
var1 = 'PRINCE GAJERA'
var2 = 'hello world'

np.char.str_len(var1)

np.int64(13)

In [ ]:
# var2.upper()
np.char.upper(var2)

array('HELLO WORLD', dtype='<U11')

In [ ]:
# var1.lower()
np.char.lower(var1)

array('prince gajera', dtype='<U13')

In [ ]:
np.char.capitalize(var2)

array('Hello world', dtype='<U11')

In [ ]:
np.char.swapcase(var2)

array('HELLO WORLD', dtype='<U11')

In [ ]:
np.char.split(var2)

array(list(['hello', 'world']), dtype=object)

In [ ]:
np.char.count(var2, 'l')

np.int64(3)

In [ ]:
np.char.find(var2, 'o')

np.int64(4)

In [ ]:
np.char.replace(var1, 'PRINCE', 'AXIT')

array('AXIT GAJERA', dtype='<U11')

In [ ]:
np.char.lstrip('      world')

np.str_('world')

In [ ]:
np.char.rstrip('world     ')

np.str_('world')

In [ ]:
np.char.strip('  hello     ')

np.str_('hello')

In [ ]:
np.char.equal(var1, var2)

array(False)

In [ ]:
np.char.not_equal(var1, var2)

array(True)

In [ ]:
arr = np.array(['python','numpy','machine learning'])

np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'MACHINE LEARNING'], dtype='<U16')

In [ ]:
arr = np.array([12,16,28,192,1162])
arr

array([  12,   16,   28,  192, 1162])

In [ ]:
arr_1 = np.array([12,3,4,40])
arr_1

array([12,  3,  4, 40])

In [ ]:
help(np.char)

Help on package numpy.char in numpy:

NAME
    numpy.char

DESCRIPTION
    This module contains a set of functions for vectorized string
    operations and methods.

    .. note::
       The `chararray` class exists for backwards compatibility with
       Numarray, it is not recommended for new development. Starting from numpy
       1.4, if one needs arrays of strings, it is recommended to use arrays of
       `dtype` `object_`, `bytes_` or `str_`, and use the free functions
       in the `numpy.char` module for fast vectorized string operations.

    Some methods will only be available if the corresponding string method is
    available in your version of Python.

    The preferred alias for `defchararray` is `numpy.char`.

PACKAGE CONTENTS


CLASSES
    numpy.ndarray(builtins.object)
        chararray

    class chararray(numpy.ndarray)
     |  chararray(shape, itemsize=1, unicode=False, buffer=None, offset=0, strides=None, order='C')
     |
     |  chararray(shape, itemsize=1, unicode=False, buffer=None, offset=0,
     |            strides=None, order=None)
     |
     |  Provides a convenient view on arrays of string and unicode values.
     |
     |  .. note::
     |     The `chararray` class exists for backwards compatibility with
     |     Numarray, it is not recommended for new development. Starting from numpy
     |     1.4, if one needs arrays of strings, it is recommended to use arrays of
     |     `dtype` `~numpy.object_`, `~numpy.bytes_` or `~numpy.str_`, and use
     |     the free functions in the `numpy.char` module for fast vectorized
     |     string operations.
     |
     |  Versus a NumPy array of dtype `~numpy.bytes_` or `~numpy.str_`, this
     |  class adds the following functionality:
     |
     |  1) values automatically have whitespace removed from the end
     |     when indexed
     |
     |  2) comparison operators automatically remove whitespace from the
     |     end when comparing values
     |
     |  3) vectorized string operations are provided as methods
     |     (e.g. `.endswith`) and infix operators (e.g. ``"+", "*", "%"``)
     |
     |  chararrays should be created using `numpy.char.array` or
     |  `numpy.char.asarray`, rather than this constructor directly.
     |
     |  This constructor creates the array, using `buffer` (with `offset`
     |  and `strides`) if it is not ``None``. If `buffer` is ``None``, then
     |  constructs a new array with `strides` in "C order", unless both
     |  ``len(shape) >= 2`` and ``order='F'``, in which case `strides`
     |  is in "Fortran order".
     |
     |  Methods
     |  -------
     |  astype
     |  argsort
     |  copy
     |  count
     |  decode
     |  dump
     |  dumps
     |  encode
     |  endswith
     |  expandtabs
     |  fill
     |  find
     |  flatten
     |  getfield
     |  index
     |  isalnum
     |  isalpha
     |  isdecimal
     |  isdigit
     |  islower
     |  isnumeric
     |  isspace
     |  istitle
     |  isupper
     |  item
     |  join
     |  ljust
     |  lower
     |  lstrip
     |  nonzero
     |  put
     |  ravel
     |  repeat
     |  replace
     |  reshape
     |  resize
     |  rfind
     |  rindex
     |  rjust
     |  rsplit
     |  rstrip
     |  searchsorted
     |  setfield
     |  setflags
     |  sort
     |  split
     |  splitlines
     |  squeeze
     |  startswith
     |  strip
     |  swapaxes
     |  swapcase
     |  take
     |  title
     |  tofile
     |  tolist
     |  tostring
     |  translate
     |  transpose
     |  upper
     |  view
     |  zfill
     |
     |  Parameters
     |  ----------
     |  shape : tuple
     |      Shape of the array.
     |  itemsize : int, optional
     |      Length of each array element, in number of characters. Default is 1.
     |  unicode : bool, optional
     |      Are the array elements of type unicode (True) or string (False).
     |      Default is False.
     |  buffer : object exposing the buffer interface or str, optional
     |      Memory address of the start of the array data.  Default is None,
     |      in which case a new array is created.
     |  offset : int, optional
     |      Fixed stride displacement from the beginning of an axis?
     |      Default is 0. Needs to be >=0.
     |  strides : array_like of ints, optional
     |      Strides for the array (see `~numpy.ndarray.strides` for
     |      full description). Default is None.
     |  order : {'C', 'F'}, optional
     |      The order in which the array data is stored in memory: 'C' ->
     |      "row major" order (the default), 'F' -> "column major"
     |      (Fortran) order.
     |
     |  Examples
     |  --------
     |  >>> charar = np.char.chararray((3, 3))
     |  >>> charar[:] = 'a'
     |  >>> charar
     |  chararray([[b'a', b'a', b'a'],
     |             [b'a', b'a', b'a'],
     |             [b'a', b'a', b'a']], dtype='|S1')
     |
     |  >>> charar = np.char.chararray(charar.shape, itemsize=5)
     |  >>> charar[:] = 'abc'
     |  >>> charar
     |  chararray([[b'abc', b'abc', b'abc'],
     |             [b'abc', b'abc', b'abc'],
     |             [b'abc', b'abc', b'abc']], dtype='|S5')
     |
     |  Method resolution order:
     |      chararray
     |      numpy.ndarray
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __add__(self, other) from numpy._core.defchararray.chararray
     |      Return (self + other), that is string concatenation,
     |      element-wise for a pair of array_likes of str or unicode.
     |
     |      See Also
     |      --------
     |      add
     |
     |  __array_finalize__(self, obj) from numpy._core.defchararray.chararray
     |      a.__array_finalize__(obj, /)
     |
     |      Present so subclasses can call super. Does nothing.
     |
     |  __array_wrap__(self, arr, context=None, return_scalar=False) from numpy._core.defchararray.chararray
     |      a.__array_wrap__(array[, context], /)
     |
     |      Returns a view of `array` with the same type as self.
     |
     |  __eq__(self, other) from numpy._core.defchararray.chararray
     |      Return (self == other) element-wise.
     |
     |      See Also
     |      --------
     |      equal
     |
     |  __ge__(self, other) from numpy._core.defchararray.chararray
     |      Return (self >= other) element-wise.
     |
     |      See Also
     |      --------
     |      greater_equal
     |
     |  __getitem__(self, obj) from numpy._core.defchararray.chararray
     |      Return self[key].
     |
     |  __gt__(self, other) from numpy._core.defchararray.chararray
     |      Return (self > other) element-wise.
     |
     |      See Also
     |      --------
     |      greater
     |
     |  __le__(self, other) from numpy._core.defchararray.chararray
     |      Return (self <= other) element-wise.
     |
     |      See Also
     |      --------
     |      less_equal
     |
     |  __lt__(self, other) from numpy._core.defchararray.chararray
     |      Return (self < other) element-wise.
     |
     |      See Also
     |      --------
     |      less
     |
     |  __mod__(self, i) from numpy._core.defchararray.chararray
     |      Return (self % i), that is pre-Python 2.6 string formatting
     |      (interpolation), element-wise for a pair of array_likes of `bytes_`
     |      or `str_`.
     |
     |      See Also
     |      --------
     |      mod
     |
     |  __mul__(self, i) from numpy._core.defchararray.chararray
     |      Return (self * i), that is string multiple concatenation,
     |      element-wise.
     |
     |      See Also
     |      --------
     |      multiply
     |
     |  __ne__(self, other) from numpy._core.defchararray.chararray
     |      Return (self != other) element-wise.
     |
     |      See Also
     |      --------
     |      not_equal
     |
     |  __radd__(self, other) from numpy._core.defchararray.chararray
     |      Return (other + self), that is string concatenation,
     |      element-wise for a pair of array_likes of `bytes_` or `str_`.
     |
     |      See Also
     |      --------
     |      add
     |
     |  __rmod__(self, other) from numpy._core.defchararray.chararray
     |      Return value%self.
     |
     |  __rmul__(self, i) from numpy._core.defchararray.chararray
     |      Return (self * i), that is string multiple concatenation,
     |      element-wise.
     |
     |      See Also
     |      --------
     |      multiply
     |
     |  argsort(self, axis=-1, kind=None, order=None) from numpy._core.defchararray.chararray
     |      a.argsort(axis=-1, kind=None, order=None)
     |
     |      Returns the indices that would sort this array.
     |
     |      Refer to `numpy.argsort` for full documentation.
     |
     |      See Also
     |      --------
     |      numpy.argsort : equivalent function
     |
     |  capitalize(self) from numpy._core.defchararray.chararray
     |      Return a copy of `self` with only the first character of each element
     |      capitalized.
     |
     |      See Also
     |      --------
     |      char.capitalize
     |
     |  center(self, width, fillchar=' ') from numpy._core.defchararray.chararray
     |      Return a copy of `self` with its elements centered in a
     |      string of length `width`.
     |
     |      See Also
     |      --------
     |      center
     |
     |  count(self, sub, start=0, end=None) from numpy._core.defchararray.chararray
     |      Returns an array with the number of non-overlapping occurrences of
     |      substring `sub` in the range [`start`, `end`].
     |
     |      See Also
     |      --------
     |      char.count
     |
     |  decode(self, encoding=None, errors=None) from numpy._core.defchararray.chararray
     |      Calls ``bytes.decode`` element-wise.
     |
     |      See Also
     |      --------
     |      char.decode
     |
     |  encode(self, encoding=None, errors=None) from numpy._core.defchararray.chararray
     |      Calls :meth:`str.encode` element-wise.
     |
     |      See Also
     |      --------
     |      char.encode
     |
     |  endswith(self, suffix, start=0, end=None) from numpy._core.defchararray.chararray
     |      Returns a boolean array which is `True` where the string element
     |      in `self` ends with `suffix`, otherwise `False`.
     |
     |      See Also
     |      --------
     |      char.endswith
     |
     |  expandtabs(self, tabsize=8) from numpy._core.defchararray.chararray
     |      Return a copy of each string element where all tab characters are
     |      replaced by one or more spaces.
     |
     |      See Also
     |      --------
     |      char.expandtabs
     |
     |  find(self, sub, start=0, end=None) from numpy._core.defchararray.chararray
     |      For each element, return the lowest index in the string where
     |      substring `sub` is found.
     |
     |      See Also
     |      --------
     |      char.find
     |
     |  index(self, sub, start=0, end=None) from numpy._core.defchararray.chararray
     |      Like `find`, but raises :exc:`ValueError` when the substring is not
     |      found.
     |
     |      See Also
     |      --------
     |      char.index
     |
     |  isalnum(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if all characters in the string
     |      are alphanumeric and there is at least one character, false
     |      otherwise.
     |
     |      See Also
     |      --------
     |      char.isalnum
     |
     |  isalpha(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if all characters in the string
     |      are alphabetic and there is at least one character, false
     |      otherwise.
     |
     |      See Also
     |      --------
     |      char.isalpha
     |
     |  isdecimal(self) from numpy._core.defchararray.chararray
     |      For each element in `self`, return True if there are only
     |      decimal characters in the element.
     |
     |      See Also
     |      --------
     |      char.isdecimal
     |
     |  isdigit(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if all characters in the string are
     |      digits and there is at least one character, false otherwise.
     |
     |      See Also
     |      --------
     |      char.isdigit
     |
     |  islower(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if all cased characters in the
     |      string are lowercase and there is at least one cased character,
     |      false otherwise.
     |
     |      See Also
     |      --------
     |      char.islower
     |
     |  isnumeric(self) from numpy._core.defchararray.chararray
     |      For each element in `self`, return True if there are only
     |      numeric characters in the element.
     |
     |      See Also
     |      --------
     |      char.isnumeric
     |
     |  isspace(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if there are only whitespace
     |      characters in the string and there is at least one character,
     |      false otherwise.
     |
     |      See Also
     |      --------
     |      char.isspace
     |
     |  istitle(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if the element is a titlecased
     |      string and there is at least one character, false otherwise.
     |
     |      See Also
     |      --------
     |      char.istitle
     |
     |  isupper(self) from numpy._core.defchararray.chararray
     |      Returns true for each element if all cased characters in the
     |      string are uppercase and there is at least one character, false
     |      otherwise.
     |
     |      See Also
     |      --------
     |      char.isupper
     |
     |  join(self, seq) from numpy._core.defchararray.chararray
     |      Return a string which is the concatenation of the strings in the
     |      sequence `seq`.
     |
     |      See Also
     |      --------
     |      char.join
     |
     |  ljust(self, width, fillchar=' ') from numpy._core.defchararray.chararray
     |      Return an array with the elements of `self` left-justified in a
     |      string of length `width`.
     |
     |      See Also
     |      --------
     |      char.ljust
     |
     |  lower(self) from numpy._core.defchararray.chararray
     |      Return an array with the elements of `self` converted to
     |      lowercase.
     |
     |      See Also
     |      --------
     |      char.lower
     |
     |  lstrip(self, chars=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy with the leading characters
     |      removed.
     |
     |      See Also
     |      --------
     |      char.lstrip
     |
     |  partition(self, sep) from numpy._core.defchararray.chararray
     |      Partition each element in `self` around `sep`.
     |
     |      See Also
     |      --------
     |      partition
     |
     |  replace(self, old, new, count=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy of the string with all
     |      occurrences of substring `old` replaced by `new`.
     |
     |      See Also
     |      --------
     |      char.replace
     |
     |  rfind(self, sub, start=0, end=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return the highest index in the string
     |      where substring `sub` is found, such that `sub` is contained
     |      within [`start`, `end`].
     |
     |      See Also
     |      --------
     |      char.rfind
     |
     |  rindex(self, sub, start=0, end=None) from numpy._core.defchararray.chararray
     |      Like `rfind`, but raises :exc:`ValueError` when the substring `sub` is
     |      not found.
     |
     |      See Also
     |      --------
     |      char.rindex
     |
     |  rjust(self, width, fillchar=' ') from numpy._core.defchararray.chararray
     |      Return an array with the elements of `self`
     |      right-justified in a string of length `width`.
     |
     |      See Also
     |      --------
     |      char.rjust
     |
     |  rpartition(self, sep) from numpy._core.defchararray.chararray
     |      Partition each element in `self` around `sep`.
     |
     |      See Also
     |      --------
     |      rpartition
     |
     |  rsplit(self, sep=None, maxsplit=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a list of the words in
     |      the string, using `sep` as the delimiter string.
     |
     |      See Also
     |      --------
     |      char.rsplit
     |
     |  rstrip(self, chars=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy with the trailing
     |      characters removed.
     |
     |      See Also
     |      --------
     |      char.rstrip
     |
     |  split(self, sep=None, maxsplit=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a list of the words in the
     |      string, using `sep` as the delimiter string.
     |
     |      See Also
     |      --------
     |      char.split
     |
     |  splitlines(self, keepends=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a list of the lines in the
     |      element, breaking at line boundaries.
     |
     |      See Also
     |      --------
     |      char.splitlines
     |
     |  startswith(self, prefix, start=0, end=None) from numpy._core.defchararray.chararray
     |      Returns a boolean array which is `True` where the string element
     |      in `self` starts with `prefix`, otherwise `False`.
     |
     |      See Also
     |      --------
     |      char.startswith
     |
     |  strip(self, chars=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy with the leading and
     |      trailing characters removed.
     |
     |      See Also
     |      --------
     |      char.strip
     |
     |  swapcase(self) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy of the string with
     |      uppercase characters converted to lowercase and vice versa.
     |
     |      See Also
     |      --------
     |      char.swapcase
     |
     |  title(self) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a titlecased version of the
     |      string: words start with uppercase characters, all remaining cased
     |      characters are lowercase.
     |
     |      See Also
     |      --------
     |      char.title
     |
     |  translate(self, table, deletechars=None) from numpy._core.defchararray.chararray
     |      For each element in `self`, return a copy of the string where
     |      all characters occurring in the optional argument
     |      `deletechars` are removed, and the remaining characters have
     |      been mapped through the given translation table.
     |
     |      See Also
     |      --------
     |      char.translate
     |
     |  upper(self) from numpy._core.defchararray.chararray
     |      Return an array with the elements of `self` converted to
     |      uppercase.
     |
     |      See Also
     |      --------
     |      char.upper
     |
     |  zfill(self, width) from numpy._core.defchararray.chararray
     |      Return the numeric string left-filled with zeros in a string of
     |      length `width`.
     |
     |      See Also
     |      --------
     |      char.zfill
     |
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(12,16)

array([12, 13, 14, 15])

In [ ]:
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
arr_2 = [40,50,60]
arr_3 = [10,20,30]
print('sum of arr_2 & arr_3 is', np.sum([arr_2,arr_3]))

sum of arr_2 & arr_3 is 210

In [ ]:
np.mean([arr_2, arr_3]) #210/6
np.median([arr_2, arr_3])

np.float64(35.0)

In [ ]:
np.std([arr_2, arr_3])

np.float64(17.07825127659933)

In [ ]:
np.mean(arr_3)

np.float64(20.0)

In [ ]:
np.var(arr_3)

np.float64(66.66666666666667)

In [ ]:
arr_4 = np.arange(1,10)
arr_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_5 = np.array([[12,16],[17,18]])
arr_5

array([[12, 16],
       [17, 18]])

In [ ]:
np.transpose(arr_5)

array([[12, 17],
       [16, 18]])

In [ ]:
arr_5.flatten()

array([12, 16, 17, 18])

In [ ]:
arr_6 = [67,23,89,1]
# np.sort(arr_6)
# np.sort(arr_6)[::-1]
np.sort(arr_6, kind='mergesort')
np.sort([67,23,89,1])

array([ 1, 23, 67, 89])

In [ ]:
np.unique([1,2,2,3,3,4,4,5,5,6,6,6,3])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.where(arr_6 == 1)
# np.where(arr>28)

/tmp/ipykernel_463/556820667.py:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  np.where(arr_6 == 1)

(array([], dtype=int64),)

In [3]:
import numpy as np
np.nonzero([0,2,0,0,5,0,8])

(array([1, 4, 6]),)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array([1,2])
b=np.array([3,4])

np.concatenate((a,b))

array([1, 2, 3, 4])

# **DAY - 2**

In [ ]:
import numpy as np

In [11]:
arr_7 = np.array([1,2,3,4])
type(arr_7)
# arr_7.dtype

numpy.ndarray

In [ ]:
#for cheak size
arr_7.size

4

In [ ]:
arr_7.ndim # cheak dimention

1

In [ ]:
arr_8 = np.array([[4,6],[8,10]])
arr_8.size

4

In [ ]:
arr_8.ndim

2

In [ ]:
arr_8.shape # shows rows and columns

(2, 2)

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
mx_ones = np.ones((2,3))
mx_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
mx_ones.dtype

dtype('float64')

In [13]:
mx_ones = mx_ones.astype(int)
display(mx_ones)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
mx_ones.dtype

dtype('int64')

In [17]:
arr_9 = np.arange(11,31,2)
# arr_9 = np.array([1,2,3,4,5,6,7,8,9])
arr_9.reshape(2,5) # 2D
# arr_9

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [18]:
arr_9.reshape(1,10) #1D

array([[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]])

In [19]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [20]:
arr_9.ravel() #1D

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [21]:
arr_9.flatten()

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [26]:
A = np.array([[2,4],[1,3]])
B = np.array([[5,7],[6,8]])
A @ B
# A.shape

(2, 2)

In [23]:
np.max(arr_9)

np.int64(29)

In [24]:
np.min(arr_9)

np.int64(11)

In [27]:
np.sum((A,B))

np.int64(36)

In [28]:
np.multiply(A,B)

array([[10, 28],
       [ 6, 24]])

In [29]:
np.add(A,B)

array([[ 7, 11],
       [ 7, 11]])

In [30]:
np.diff((A,B))

array([[[2],
        [2]],

       [[2],
        [2]]])

In [31]:
np.divide(A,B)

array([[0.4       , 0.57142857],
       [0.16666667, 0.375     ]])

# **DAY 3**

In [ ]:
import numpy as np

In [32]:
var_1 = np.array([1, 2, -2, 6, -9, -7])

In [36]:
positive_numbers = var_1[var_1 > 0]
print('Positive numbers:', positive_numbers)

Positive numbers: [1 2 6]

In [37]:
negative_numbers = var_1[var_1 < 0]
print('Negative numbers:', negative_numbers)

Negative numbers: [-2 -9 -7]

In [38]:
positive_indices = np.where(var_1 > 0)
print('Indices of positive numbers:', positive_indices)

Indices of positive numbers: (array([0, 1, 3]),)

In [39]:
negative_indices = np.where(var_1 < 0)
print('Indices of negative numbers:', negative_indices)

Indices of negative numbers: (array([2, 4, 5]),)

In [40]:
neg_aws = var_1[var_1 < 0]
print(neg_aws)

[-2 -9 -7]

In [41]:
pos_ans = var_1[var_1 > 0]
print(pos_ans)

[1 2 6]

In [42]:
index = [2,4,5]
answer = var_1[index]
print(answer)

[-2 -9 -7]

# **DAY 4 - Pandas**

**What is panda ?
Why pandas ?
Series = 1D to 2D.
Data Frame.
Reading Data.
Exploring Data.
Selecting Data.
Modifying Data.
Sorting Data.
Agricating Data.
Handling Missing values.
Applying Function.**

**What is pandas ?**

In [45]:
import pandas as pd

In [51]:
var_1 = [1, 2, 3]
pd.Series(var_1)
# type(var_1)

0    1
1    2
2    3
dtype: int64

In [49]:
var_2 = [2, 3, 4, 5, 6 ,7]
lab = ['p', 'r', 'i', 'n', 'c', 'e']
sr_2 = pd.Series(var_2, index=lab)
# sr_2 = pd.Series(var_2, index=['p', 'r', 'i', 'n', 'c', 'e'])
print(sr_2)

p    2
r    3
i    4
n    5
c    6
e    7
dtype: int64

In [52]:
var_3 = [[1,2,3],
         [4,5,6]]
sr_3 = pd.Series(var_3)
sr_3
print(type(sr_3))

<class 'pandas.core.series.Series'>

In [53]:
print(sr_3)

0    [1, 2, 3]
1    [4, 5, 6]
dtype: object

In [57]:
df_2 = pd.DataFrame(sr_3)
# df_2 = pd.DataFrame(var_3)
print(type(df_2))
df_2

<class 'pandas.core.frame.DataFrame'>

   0  1  2
0  1  2  3
1  4  5  6

In [ ]:
df_2 = pd.DataFrame(sr_3, columns=['A'], index=['a', 'b'])
print(type(df_2))
df_2

<class 'pandas.core.frame.DataFrame'>

     A
a  NaN
b  NaN

In [ ]:
data = {
    'Name':['Prince', 'Smit', 'Mayur'],
    'Roll no': [47, 34]
    }
print(data)

{'Name': ['Prince', 'Smit', 'Mayur'], 'Roll no': [47, 34]}

In [ ]:
nes_list = [['prince',21], ['smit',20], ['hardik',20]]
data1 = pd.DataFrame(nes_list, columns=['name','age'])
print(data1)

     name  age
0  prince   21
1    smit   20
2  hardik   20

In [ ]:
d1 = np.array([1,2,3,4])
d2 = np.array([5,6,7,8])
d3 = np.array([9,10,11,12])
data_fr = {
    'df1':d1,
    'df2':d2,
    'df3':d3
}
print(data_fr)

{'df1': array([1, 2, 3, 4]), 'df2': array([5, 6, 7, 8]), 'df3': array([ 9, 10, 11, 12])}

In [ ]:
df = pd.DataFrame(data_fr)
print(df)

   df1  df2  df3
0    1    5    9
1    2    6   10
2    3    7   11
3    4    8   12

## **Dataset Upload**

In [59]:
from google.colab import files
upload = files.upload()

Saving archive (1).zip to archive (1).zip

In [60]:
!mv "/content/archive (1).zip" /content/ecommerce.zip

In [61]:
!unzip /content/ecommerce.zip -d /content/ecommerce_data

Archive:  /content/ecommerce.zip
  inflating: /content/ecommerce_data/ecommerce_sales_analytics_5000.csv

In [62]:
!ls -R /content/ecommerce_data

/content/ecommerce_data:
ecommerce_sales_analytics_5000.csv

In [63]:
df = pd.read_csv("/content/ecommerce_data/ecommerce_sales_analytics_5000.csv")

In [ ]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [67]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5000 entries, 0 to 4999
Series name: product_category
Non-Null Count  Dtype
--------------  -----
5000 non-null   object
dtypes: object(1)
memory usage: 39.2+ KB

In [69]:
df['product_category'].tail(20)

4980           Home
4981         Beauty
4982       Clothing
4983           Home
4984       Clothing
4985       Clothing
4986       Clothing
4987    Electronics
4988       Clothing
4989       Clothing
4990           Home
4991           Home
4992           Home
4993    Electronics
4994           Home
4995       Clothing
4996         Beauty
4997         Beauty
4998    Electronics
4999           Home
Name: product_category, dtype: object

In [ ]:
df["product_category"].unique()

array(['Beauty', 'Clothing', 'Electronics', 'Home'], dtype=object)

In [ ]:
df.shape

(5000, 12)

In [ ]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [ ]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [ ]:
df_rivers = pd.read_json("/content/rivers.json")

In [ ]:
df_rivers.head()

                                              rivers
0  {'name': 'Nile', 'length_km': 6650, 'drainage_...
1  {'name': 'Amazon', 'length_km': 6400, 'drainag...
2  {'name': 'Yangtze', 'length_km': 6300, 'draina...
3  {'name': 'Mississippi-Missouri', 'length_km': ...
4  {'name': 'Yenisei', 'length_km': 5539, 'draina...

In [ ]:
import json

with open("/content/rivers.json", "r") as f:
    rivers = json.load(f)

type(rivers)

dict

In [ ]:
print(rivers)

{'rivers': [{'name': 'Nile', 'length_km': 6650, 'drainage_km2': 3349000, 'countries': ['Egypt', 'Sudan', 'South Sudan', 'Ethiopia', 'Uganda'], 'mouth': 'Mediterranean Sea', 'continent': 'Africa'}, {'name': 'Amazon', 'length_km': 6400, 'drainage_km2': 7050000, 'countries': ['Brazil', 'Peru', 'Colombia'], 'mouth': 'Atlantic Ocean', 'continent': 'South America'}, {'name': 'Yangtze', 'length_km': 6300, 'drainage_km2': 1808500, 'countries': ['China'], 'mouth': 'East China Sea', 'continent': 'Asia'}, {'name': 'Mississippi-Missouri', 'length_km': 6275, 'drainage_km2': 2980000, 'countries': ['United States'], 'mouth': 'Gulf of Mexico', 'continent': 'North America'}, {'name': 'Yenisei', 'length_km': 5539, 'drainage_km2': 2580000, 'countries': ['Russia', 'Mongolia'], 'mouth': 'Kara Sea', 'continent': 'Asia'}, {'name': 'Yellow River', 'length_km': 5464, 'drainage_km2': 752546, 'countries': ['China'], 'mouth': 'Bohai Sea', 'continent': 'Asia'}, {'name': 'Ob', 'length_km': 5410, 'drainage_km2': 2990000, 'countries': ['Russia', 'Kazakhstan', 'China'], 'mouth': 'Gulf of Ob', 'continent': 'Asia'}, {'name': 'Paraná', 'length_km': 4880, 'drainage_km2': 2582672, 'countries': ['Brazil', 'Paraguay', 'Argentina'], 'mouth': 'Atlantic Ocean', 'continent': 'South America'}, {'name': 'Congo', 'length_km': 4700, 'drainage_km2': 4014500, 'countries': ['DR Congo', 'Central African Republic', 'Angola'], 'mouth': 'Atlantic Ocean', 'continent': 'Africa'}, {'name': 'Amur', 'length_km': 4444, 'drainage_km2': 1855000, 'countries': ['Russia', 'China', 'Mongolia'], 'mouth': 'Sea of Okhotsk', 'continent': 'Asia'}, {'name': 'Mekong', 'length_km': 4350, 'drainage_km2': 795000, 'countries': ['China', 'Myanmar', 'Laos', 'Thailand', 'Cambodia', 'Vietnam'], 'mouth': 'South China Sea', 'continent': 'Asia'}, {'name': 'Ganges', 'length_km': 2525, 'drainage_km2': 1016124, 'countries': ['India', 'Bangladesh'], 'mouth': 'Bay of Bengal', 'continent': 'Asia'}, {'name': 'Danube', 'length_km': 2850, 'drainage_km2': 817000, 'countries': ['Germany', 'Austria', 'Hungary', 'Serbia', 'Romania'], 'mouth': 'Black Sea', 'continent': 'Europe'}, {'name': 'Rhine', 'length_km': 1233, 'drainage_km2': 185000, 'countries': ['Switzerland', 'Germany', 'France', 'Netherlands'], 'mouth': 'North Sea', 'continent': 'Europe'}, {'name': 'Thames', 'length_km': 346, 'drainage_km2': 12935, 'countries': ['United Kingdom'], 'mouth': 'North Sea', 'continent': 'Europe'}]}

In [ ]:
df.dtypes

order_id              int64
order_date           object
customer_id           int64
product_category     object
region               object
quantity              int64
unit_price          float64
discount            float64
payment_method       object
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

In [ ]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [ ]:
df['quantity'].value_counts()

quantity
7    775
2    721
4    718
6    713
1    704
5    698
3    671
Name: count, dtype: int64

In [ ]:
df['quantity'].astype(object)

0       7
1       7
2       3
3       5
4       5
       ..
4995    2
4996    3
4997    3
4998    4
4999    7
Name: quantity, Length: 5000, dtype: object

# **to convert (object) -> (float & int) possible but (float & int) -> (object) not possible**

In [ ]:
# df['discount'] = df['discount'].astype(object) = aa karva thi aapde discount ne int mathi obj banavi chi ane aapda dataset ma discount colom ma int na badle obj thay jase.
# df['discount'].astype(object) = aane aa karva thi same aapde discount ne int mathi obj banavi chi pann aa nu output je niche ave dtype: object aavu kaik e khali dekhase k tame dtype change kriyu pann dataset ma change nai thyu hoi.
df['discount'].astype(object)

0       0.28
1       0.09
2       0.31
3       0.02
4       0.33
        ...
4995    0.27
4996    0.14
4997    0.24
4998    0.21
4999    0.34
Name: discount, Length: 5000, dtype: object

In [ ]:
df['discount'].dtypes

dtype('float64')

In [ ]:
df['total_discount_amount'] = df['region'].astype(str) + df['discount'].astype(str)
display(df.head())

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_discount_amount
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,South0.28
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,South0.09
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,East0.31
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,West0.02
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,West0.33

# **Sorting Data**

In [ ]:
df_sorted = df.sort_values(by='customer_rating', ascending=True)
# display(df_sorted.head())
# display(df_sorted.tail())
display(df_sorted)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_discount_amount
4511,14512,5/9/2034,1000,Electronics,North,1,594.11,0.17,COD,6,1.0,493.11,North0.17
586,10587,8/10/2023,1046,Clothing,North,7,47.75,0.14,COD,2,1.0,287.46,North0.14
2465,12466,10/1/2028,1989,Electronics,South,5,22.84,0.10,Card,3,1.0,102.78,South0.1
631,10632,9/24/2023,1998,Clothing,North,4,517.73,0.30,Wallet,6,1.0,1449.64,North0.3
633,10634,9/26/2023,1446,Electronics,East,3,218.01,0.31,Wallet,4,1.0,451.28,East0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904,11905,3/20/2027,1490,Clothing,South,5,15.77,0.14,Card,4,5.0,67.81,South0.14
3617,13618,11/27/2031,1396,Home,East,2,254.47,0.04,COD,2,5.0,488.58,East0.04
4940,14941,7/12/2035,1900,Beauty,West,4,424.78,0.08,COD,3,5.0,1563.19,West0.08
2193,12194,1/3/2028,1954,Home,East,3,462.78,0.33,COD,6,5.0,930.19,East0.33
2217,12218,1/27/2028,1223,Beauty,North,2,465.88,0.02,Card,1,5.0,913.12,North0.02

In [ ]:
df_sorted = df.sort_values(by='total_discount_amount', ascending=True)
display(df_sorted)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_discount_amount
807,10808,3/18/2024,1024,Home,East,4,569.13,0.00,Card,8,3.6,2276.52,East0.0
680,10681,11/12/2023,1607,Clothing,East,1,157.42,0.00,Card,3,2.0,157.42,East0.0
1796,11797,12/2/2026,1058,Home,East,7,194.77,0.00,Card,4,1.8,1363.39,East0.0
4821,14822,3/15/2035,1486,Clothing,East,4,210.16,0.00,Card,2,1.1,840.64,East0.0
44,10045,2/14/2022,1699,Home,East,3,31.16,0.00,Wallet,6,3.3,93.48,East0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,13949,10/23/2032,1312,Home,West,7,385.50,0.35,Wallet,11,3.9,1754.02,West0.35
4962,14963,8/3/2035,1354,Electronics,West,2,260.25,0.35,COD,7,2.3,338.32,West0.35
94,10095,4/5/2022,1771,Home,West,2,387.82,0.35,COD,2,3.4,504.17,West0.35
3901,13902,9/6/2032,1269,Home,West,2,320.30,0.35,Card,6,1.2,416.39,West0.35
458,10459,4/4/2023,1658,Clothing,West,4,346.79,0.35,COD,6,4.3,901.65,West0.35

In [ ]:
df.rename(columns={'revenue': 'total_revenueperID'})
print(df.columns)

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'total_discount_amount'],
      dtype='object')

In [ ]:
df = df.rename(columns={'revenue': 'total_perID'})
print(df)

      order_id order_date  customer_id product_category region  quantity  \
0        10001   1/1/2022         1102           Beauty  South         7
1        10002   1/2/2022         1435         Clothing  South         7
2        10003   1/3/2022         1860           Beauty   East         3
3        10004   1/4/2022         1270      Electronics   West         5
4        10005   1/5/2022         1106         Clothing   West         5
...        ...        ...          ...              ...    ...       ...
4995     14996   9/5/2035         1289         Clothing   West         2
4996     14997   9/6/2035         1294           Beauty  North         3
4997     14998   9/7/2035         1450           Beauty   West         3
4998     14999   9/8/2035         1903      Electronics  South         4
4999     15000   9/9/2035         1214             Home   East         7

      unit_price  discount payment_method  delivery_days  customer_rating  \
0         373.65      0.28         Wallet             10              4.7
1          47.74      0.09           Card              6              3.9
2         311.28      0.31            COD              6              2.5
3         524.47      0.02         Wallet              6              1.6
4         139.87      0.33         Wallet              4              4.9
...          ...       ...            ...            ...              ...
4995      371.74      0.27            COD              3              2.3
4996      553.67      0.14            COD             11              2.2
4997       77.22      0.24         Wallet              6              3.4
4998      138.41      0.21            COD              4              2.8
4999      231.58      0.34            COD              5              3.9

      total_perID total_discount_amount
0         1883.20             South0.28
1          304.10             South0.09
2          644.35              East0.31
3         2569.90              West0.02
4          468.56              West0.33
...           ...                   ...
4995       542.74              West0.27
4996      1428.47             North0.14
4997       176.06              West0.24
4998       437.38             South0.21
4999      1069.90              East0.34

[5000 rows x 13 columns]